volumes:
  project_slug_local_postgres_data: {}
  project_slug_local_postgres_data_backups: {}
  project_slug_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: project_slug_local_django
    container_name: project_slug_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '127.0.0.1:8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: project_slug_production_postgres
    container_name: project_slug_local_postgres
    volumes:
      - project_slug_local_postgres_data:/var/lib/postgresql/data
      - project_slug_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: project_slug_local_mailpit
    ports:
      - "127.0.0.1:8025:8025"

  redis:
    image: docker.io/redis:7.2
    container_name: project_slug_local_redis
    volumes:
      - project_slug_local_redis_data:/data

  celeryworker:
    <<: *django
    image: project_slug_local_celeryworker
    container_name: project_slug_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: project_slug_local_celerybeat
    container_name: project_slug_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: project_slug_local_flower
    container_name: project_slug_local_flower
    ports:
      - '127.0.0.1:5555:5555'
    command: /start-flower

  frontend:
    build:
      context: .
      dockerfile: ./compose/local/frontend/Dockerfile
    image: project_slug_local_frontend
    container_name: project_slug_local_frontend
    volumes:
      - ./frontend:/app:z
      - /app/node_modules
    env_file:
      - ./.envs/.local/.frontend
    ports:
      - '127.0.0.1:5173:5173'
    command: /start
